wandb:
  project: gs_pred
cam_embd:
  embedding: null
  encode_embedding: null
  dimension: 0
  method: null
general:
  device: 0
  random_seed: 0
  num_devices: 1
  mixed_precision: true
data:
  training_resolution: 128
  subset: -1
  input_images: 1
  origin_distances: false
  znear: 0.8
  zfar: 3.2
  category: objaverse
  white_background: true
  fov: 49.134342641202636
opt:
  iterations: 20001
  base_lr: 6.3e-05
  batch_size: 8
  betas:
  - 0.9
  - 0.999
  loss: l2
  imgs_per_obj: 4
  ema:
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999
  lambda_lpips: 0.25
  pretrained_ckpt: /202421000505/wsh_project/refine_splatter/splatter-image_dpt/experiments_out/base_model/
  save_interval: 1000
  warmup_steps: 1000
  lr_decay_steps: 15000
  gradient_clip_val: 0.5
  progressive_training: true
  fusion_warmup_steps: 500
model:
  max_sh_degree: 1
  inverted_x: false
  inverted_y: true
  name: SingleUNet
  opacity_scale: 1.0
  opacity_bias: -2.0
  scale_bias: 0.02
  scale_scale: 0.003
  xyz_scale: 0.1
  xyz_bias: 0.0
  depth_scale: 1.0
  depth_bias: 0.0
  network_without_offset: false
  network_with_offset: true
  attention_resolutions:
  - 16
  num_blocks: 4
  cross_view_attention: true
  base_dim: 128
  isotropic: false
  use_dpt_fusion: true
  dpt_model_path: /202421000505/wsh_project/refine_splatter/splatter-image_dpt/scene/model_cache/dpt-large
  dpt_depth_weight: 20.0
  dpt_consistency_weight: 80.0
  dpt_fusion_weight: 100.0
logging:
  ckpt_iterations: 1000
  val_log: 10000
  loss_log: 10
  loop_log: 10000
  render_log: 10000
