# @package _global_
general:
  num_devices: 1
  mixed_precision: true

data:
  znear: 0.8
  zfar: 3.2
  category: objaverse
  white_background: true
  origin_distances: false
  training_resolution: 128
  fov: 49.134342641202636

opt:
  batch_size: 4  # 小批量，适合低内存 GPU
  iterations: 5000  # 快速训练 5000 步
  lr: 0.0001  # 学习率（参考默认配置）
  save_interval: 1000  # 每 1000 步保存 checkpoint